sudo: required
services:
  - docker

before_install:
  - docker build -t tjunction/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true  tjunction/react-test yarn test -- --coverage

after_success:
  - docker build -t tjunction/multi-client ./client
  - docker build -t tjunction/multi-nginx ./nginx
  - docker build -t tjunction/multi-server ./server
  - docker build -t tjunction/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tjunction/multi-client
  - docker push tjunction/multi-nginx
  - docker push tjunction/multi-server
  - docker push tjunction/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-524536511296
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
